CC = java
PUT = src/main/java/io/hexlet
PUT_TEST = src/test/java/io/hexlet

run:
	@$(CC) $(PUT)/App.java

test:
	./gradlew test

clean:
	./gradlew clean

bud:
	./gradlew build

build:
	./gradlew clean build
