CC = java
PUT = src/main/java/io/hexlet
PUT_TEST = src/test/java/io/hexlet

run:
	@$(CC) $(PUT)/App.java

test:
	./gradlew test

clean:
	./gradlew clean

bud:
	./gradlew build

build:
	./gradlew clean build

#console:
#	@java-console

#test:
#	@mvn test -q -o
#
#test-coverage:
#	@mvn clean test -q -o -Dexec.args="-c io.hexlet.module.Methods_48Test"
#    @mvn jacoco:report

#\\wsl$\Ubuntu\home\admint\Hexlet\Java_Klass_2_Automatic_Testing_Gradle\build\jacocoHtml\index.html
#\\wsl$\Ubuntu\home\admint\Hexlet\Java_Klass_2_Automatic_Testing_Gradle\build\jacocoHtml\index.html