flowchart TD
    node{nроверка на пустой массив}
    node1(node1)
    node2(node2)
    node3(node3)
    node4(node4)
    node5(node5)




    node --> node1
    node --> node2
    node1 --> node3
    node2 --> node3
    node1 <--> node2







%%    node6(nроверка на пустой массив)
%%    node7(проверка)
%%    node8(проверка)
%%    node9(проверка)
%%    node10(проверка)
%%    node11(проверка)







%%node --> node1









%%    subgraph one
%%node1[Form 1]
%%node2(Form 2)
%%node3([Форма 3])
%%node4[[Форма 4]]
%%node5[(Форма 5)]
%%node6((Форма 6))
%%node7>Форма 7]
%%end